/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorJugador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pildorasinformaticas
 */
public class Eliminar extends javax.swing.JFrame {

    ControladorJugador contj;
    public Eliminar() throws SQLException {
        initComponents();
        contj=new ControladorJugador();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        T_Insertar_Jugador = new javax.swing.JTextField();
        B_Eliminar_Jugador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        T_Insertar_Equipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        T_Insertar_Partido = new javax.swing.JTextField();
        B_Eliminar_Partido = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        T_Insertar_Presidente = new javax.swing.JTextField();
        B_Eliminar_Presidente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        T_Insertar_Gol = new javax.swing.JTextField();
        B_Eliminar_Gol = new javax.swing.JButton();
        B_Eliminar_Equipo1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        T_Insertar_Codigo_partido = new javax.swing.JTextField();

        jLabel1.setText("Inserte el Jugador");

        B_Eliminar_Jugador.setBackground(new java.awt.Color(204, 204, 204));
        B_Eliminar_Jugador.setText("Eliminar");
        B_Eliminar_Jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Eliminar_JugadorActionPerformed(evt);
            }
        });

        jLabel2.setText("Inserte el Equipo");

        jLabel3.setText("Inserte el Partido");

        B_Eliminar_Partido.setBackground(new java.awt.Color(204, 204, 204));
        B_Eliminar_Partido.setText("Eliminar");
        B_Eliminar_Partido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Eliminar_PartidoActionPerformed(evt);
            }
        });

        jLabel4.setText("Inserte el Presidente");

        B_Eliminar_Presidente.setBackground(new java.awt.Color(204, 204, 204));
        B_Eliminar_Presidente.setText("Eliminar");
        B_Eliminar_Presidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Eliminar_PresidenteActionPerformed(evt);
            }
        });

        jLabel5.setText("Inserte el momento del Gol");

        B_Eliminar_Gol.setBackground(new java.awt.Color(204, 204, 204));
        B_Eliminar_Gol.setText("Eliminar");
        B_Eliminar_Gol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Eliminar_GolActionPerformed(evt);
            }
        });

        B_Eliminar_Equipo1.setBackground(new java.awt.Color(204, 204, 204));
        B_Eliminar_Equipo1.setText("Eliminar");
        B_Eliminar_Equipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Eliminar_Equipo1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Inserte el Codigo del Partido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator7)
            .addComponent(jSeparator8)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 11, Short.MAX_VALUE)
                                .addComponent(T_Insertar_Jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(167, 167, 167)
                                .addComponent(B_Eliminar_Jugador))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(T_Insertar_Partido, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(B_Eliminar_Partido))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(T_Insertar_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(B_Eliminar_Equipo1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(T_Insertar_Presidente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(B_Eliminar_Presidente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(T_Insertar_Gol, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(T_Insertar_Codigo_partido, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B_Eliminar_Gol)
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T_Insertar_Jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Eliminar_Jugador))
                .addGap(35, 35, 35)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T_Insertar_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Eliminar_Equipo1))
                .addGap(27, 27, 27)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T_Insertar_Partido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Eliminar_Partido))
                .addGap(26, 26, 26)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T_Insertar_Presidente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Eliminar_Presidente))
                .addGap(35, 35, 35)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T_Insertar_Gol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(B_Eliminar_Gol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(T_Insertar_Codigo_partido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_Eliminar_JugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Eliminar_JugadorActionPerformed
        try {
            String codigo= T_Insertar_Jugador.getText();
            contj.insertarbuscareliminarj("DELETE FROM jugador WHERE jugador.codigo = "+codigo+";");
        } catch (SQLException ex) {
            Logger.getLogger(Eliminar.class.getName()).log(Level.SEVERE, null, ex);
        }
        T_Insertar_Jugador.setText(" ");
    }//GEN-LAST:event_B_Eliminar_JugadorActionPerformed

    private void B_Eliminar_PartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Eliminar_PartidoActionPerformed
        
        try {
            String codigoPartido = T_Insertar_Partido.getText();
            contj.insertarbuscareliminarj("DELETE FROM partidos WHERE partidos.codigo = "+codigoPartido+";");
        } catch (SQLException ex) {
           Logger.getLogger(Eliminar.class.getName()).log(Level.SEVERE, null, ex);
        }
        T_Insertar_Partido.setText(" ");

    }//GEN-LAST:event_B_Eliminar_PartidoActionPerformed

    private void B_Eliminar_PresidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Eliminar_PresidenteActionPerformed
   try {
            String dni = T_Insertar_Presidente.getText();
            contj.insertarbuscareliminarj("DELETE FROM presidentes WHERE dni='"+dni+"';");
        } catch (SQLException ex) {
           Logger.getLogger(Eliminar.class.getName()).log(Level.SEVERE, null, ex);
        }
        T_Insertar_Presidente.setText(" ");


    }//GEN-LAST:event_B_Eliminar_PresidenteActionPerformed

    private void B_Eliminar_GolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Eliminar_GolActionPerformed
        
        
           try {
            String codigoGol = T_Insertar_Gol.getText();
            String codigoPartido=T_Insertar_Codigo_partido.getText();
            contj.insertarbuscareliminarj("DELETE FROM goles where goles.momento_gol="+codigoGol+" and goles.codigo_partido="+codigoPartido+";");
        } catch (SQLException ex) {
           Logger.getLogger(Eliminar.class.getName()).log(Level.SEVERE, null, ex);
        }
        T_Insertar_Gol.setText(" ");
        

        
        
    }//GEN-LAST:event_B_Eliminar_GolActionPerformed

    private void B_Eliminar_Equipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Eliminar_Equipo1ActionPerformed

        
           try {
            String codigoEquipo = T_Insertar_Equipo.getText();
            contj.insertarbuscareliminarj("DELETE FROM equipo WHERE equipo.codigo = " +codigoEquipo+";");
        } catch (SQLException ex) {
           Logger.getLogger(Eliminar.class.getName()).log(Level.SEVERE, null, ex);
        }
        T_Insertar_Equipo.setText(" ");
        

    }//GEN-LAST:event_B_Eliminar_Equipo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Eliminar().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Eliminar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Eliminar_Equipo1;
    private javax.swing.JButton B_Eliminar_Gol;
    private javax.swing.JButton B_Eliminar_Jugador;
    private javax.swing.JButton B_Eliminar_Partido;
    private javax.swing.JButton B_Eliminar_Presidente;
    private javax.swing.JTextField T_Insertar_Codigo_partido;
    private javax.swing.JTextField T_Insertar_Equipo;
    private javax.swing.JTextField T_Insertar_Gol;
    private javax.swing.JTextField T_Insertar_Jugador;
    private javax.swing.JTextField T_Insertar_Partido;
    private javax.swing.JTextField T_Insertar_Presidente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
