package Vista;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author MEDC
 */
public class Insertar extends javax.swing.JFrame {

    /** Creates new form insertar */
    public Insertar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insJugador = new javax.swing.JButton();
        insEquipo = new javax.swing.JButton();
        insPresidente = new javax.swing.JButton();
        insPartido = new javax.swing.JButton();
        insGol = new javax.swing.JButton();
        actGol = new javax.swing.JButton();
        actPresidente = new javax.swing.JButton();
        actPartido = new javax.swing.JButton();
        actEquipo = new javax.swing.JButton();
        actJugador = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        diaNacJug = new javax.swing.JSpinner();
        aforo = new javax.swing.JSpinner();
        añoPresidencia = new javax.swing.JSpinner();
        golesVisitante = new javax.swing.JSpinner();
        golesLocal = new javax.swing.JSpinner();
        minuto = new javax.swing.JSpinner();
        dni = new javax.swing.JTextField();
        nombrePresidente = new javax.swing.JTextField();
        apellidosPresidente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        equipoPresidente = new javax.swing.JTextField();
        nombreEquipo = new javax.swing.JTextField();
        estadio = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        posicionJugador = new javax.swing.JTextField();
        nombreJugador = new javax.swing.JTextField();
        mesNacJug = new javax.swing.JSpinner();
        añoNacJug = new javax.swing.JSpinner();
        mesPartido = new javax.swing.JSpinner();
        diaPartido = new javax.swing.JSpinner();
        añoPartido = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        codigoPartidoFk = new javax.swing.JTextField();
        codigoJugador = new javax.swing.JTextField();
        codigoEquipoFk = new javax.swing.JTextField();
        codigoEquipoPk = new javax.swing.JTextField();
        codigoPartido = new javax.swing.JTextField();
        codigoGol = new javax.swing.JTextField();
        codigoLocal = new javax.swing.JTextField();
        codigoVisitante = new javax.swing.JTextField();
        CodigoEquipoFk2 = new javax.swing.JTextField();
        añoFund = new javax.swing.JSpinner();
        mesPartido1 = new javax.swing.JSpinner();
        diaPartido1 = new javax.swing.JSpinner();
        añoPartido1 = new javax.swing.JSpinner();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insJugador.setText("INSERTAR JUGADOR");
        getContentPane().add(insJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 682, 147, -1));

        insEquipo.setText("INSERTAR EQUIPO");
        getContentPane().add(insEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 682, 137, -1));

        insPresidente.setText("INSERTAR PRESIDENTE");
        getContentPane().add(insPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 682, 180, -1));

        insPartido.setText("INSERTAR PARTIDO");
        getContentPane().add(insPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 682, 143, -1));

        insGol.setText("INSERTAR GOL");
        getContentPane().add(insGol, new org.netbeans.lib.awtextra.AbsoluteConstraints(944, 682, 133, -1));

        actGol.setText("ACTUALIZAR GOL");
        getContentPane().add(actGol, new org.netbeans.lib.awtextra.AbsoluteConstraints(944, 733, 140, -1));

        actPresidente.setText("ACTUALIZAR PRESIDENTE");
        getContentPane().add(actPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 734, -1, -1));

        actPartido.setText("ACTUALIZAR PARTIDO");
        getContentPane().add(actPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 734, -1, -1));

        actEquipo.setText("ACTUALIZAR EQUIPO");
        getContentPane().add(actEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 734, -1, -1));

        actJugador.setText("ACTUALIZAR JUGADOR");
        getContentPane().add(actJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 734, -1, -1));

        jLabel9.setText("Estadio");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 252, 37, -1));

        jLabel11.setText("Código");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel12.setText("Aforo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 400, -1, -1));

        jLabel13.setText("Año");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 640, -1, -1));

        jLabel14.setText("Nombre");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 132, -1, -1));

        jLabel15.setText("Fundación");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 660, -1, -1));

        jLabel16.setText("Goles");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 37, -1));

        jLabel17.setText("Local");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        jLabel18.setText("Código");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 542, -1, -1));

        jLabel19.setText("Código");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 11, -1, -1));

        jLabel20.setText("Fecha");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel21.setText("Equipo 1");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 562, -1, -1));

        jLabel22.setText("Goles");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));

        jLabel23.setText("Código");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 640, -1, -1));

        jLabel24.setText("DNI");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 14, -1, -1));

        jLabel25.setText("Fecha");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 37, -1));

        jLabel26.setText("Apellidos");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, -1, -1));

        jLabel27.setText("Nacimiento");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        jLabel28.setText("Equipo");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, -1, -1));

        jLabel29.setText("Equipo");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 660, -1, -1));

        jLabel30.setText("Código");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 11, -1, -1));

        jLabel31.setText("Descripción");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 390, 60, 20));

        jLabel32.setText("Partido");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 657, -1, -1));

        jLabel33.setText("Código");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 637, -1, -1));

        jLabel36.setText("Minuto");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, -1, -1));

        jLabel37.setText("Código");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 11, -1, -1));

        jLabel38.setText("Fecha");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 341, 37, -1));

        jLabel39.setText("Equipo");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 658, -1, -1));

        jLabel40.setText("Código");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 638, -1, -1));

        jLabel41.setText("Posición");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 495, -1, -1));

        jLabel42.setText("Nacimiento");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 364, -1, -1));

        jLabel43.setText("Nombre");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 130, -1, -1));

        jLabel44.setText("Ciudad");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 497, -1, -1));

        jLabel45.setText("Nombre");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        jLabel46.setText("Año");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, -1, -1));

        jLabel47.setText("Presidencia");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, -1, -1));

        jLabel48.setText("Visitante");
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        jLabel49.setText("Código");
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 638, -1, -1));

        jLabel50.setText("Equipo 2");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 658, -1, -1));

        diaNacJug.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        getContentPane().add(diaNacJug, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        aforo.setModel(new javax.swing.SpinnerNumberModel(4000, 4000, 100000, 1));
        getContentPane().add(aforo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 397, -1, -1));

        añoPresidencia.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, 2000, 1));
        getContentPane().add(añoPresidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, -1, -1));
        getContentPane().add(golesVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));
        getContentPane().add(golesLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        minuto.setModel(new javax.swing.SpinnerNumberModel(1, 1, 120, 1));
        getContentPane().add(minuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, -1, -1));
        getContentPane().add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 11, 100, -1));
        getContentPane().add(nombrePresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 130, -1));
        getContentPane().add(apellidosPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 130, -1));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane2.setViewportView(descripcion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 390, 150, 90));
        getContentPane().add(equipoPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 130, -1));
        getContentPane().add(nombreEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 129, 100, -1));
        getContentPane().add(estadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 249, 100, -1));
        getContentPane().add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 494, 100, -1));

        posicionJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(posicionJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 492, 90, -1));
        getContentPane().add(nombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 127, 100, -1));

        mesNacJug.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        getContentPane().add(mesNacJug, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 340, -1, -1));

        añoNacJug.setModel(new javax.swing.SpinnerNumberModel(1950, 1950, 2050, 1));
        getContentPane().add(añoNacJug, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        mesPartido.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        getContentPane().add(mesPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        diaPartido.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        getContentPane().add(diaPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        añoPartido.setModel(new javax.swing.SpinnerNumberModel(1950, 1950, 2050, 1));
        getContentPane().add(añoPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 11, 800));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 0, 11, 800));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 0, 11, 800));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(872, 0, 11, 800));
        getContentPane().add(codigoPartidoFk, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, 120, -1));
        getContentPane().add(codigoJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 90, -1));
        getContentPane().add(codigoEquipoFk, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 80, -1));
        getContentPane().add(codigoEquipoPk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 100, -1));
        getContentPane().add(codigoPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 100, -1));
        getContentPane().add(codigoGol, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 100, -1));
        getContentPane().add(codigoLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 100, -1));
        getContentPane().add(codigoVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 640, 100, -1));
        getContentPane().add(CodigoEquipoFk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 650, 110, -1));

        añoFund.setModel(new javax.swing.SpinnerNumberModel(1950, 1950, 2050, 1));
        getContentPane().add(añoFund, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 650, -1, -1));

        mesPartido1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        getContentPane().add(mesPartido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, -1, -1));

        diaPartido1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        getContentPane().add(diaPartido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, -1, -1));

        añoPartido1.setModel(new javax.swing.SpinnerNumberModel(1950, 1950, 2050, 1));
        getContentPane().add(añoPartido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void posicionJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicionJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoEquipoFk2;
    private javax.swing.JButton actEquipo;
    private javax.swing.JButton actGol;
    private javax.swing.JButton actJugador;
    private javax.swing.JButton actPartido;
    private javax.swing.JButton actPresidente;
    private javax.swing.JSpinner aforo;
    private javax.swing.JTextField apellidosPresidente;
    private javax.swing.JSpinner añoFund;
    private javax.swing.JSpinner añoNacJug;
    private javax.swing.JSpinner añoPartido;
    private javax.swing.JSpinner añoPartido1;
    private javax.swing.JSpinner añoPresidencia;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField codigoEquipoFk;
    private javax.swing.JTextField codigoEquipoPk;
    private javax.swing.JTextField codigoGol;
    private javax.swing.JTextField codigoJugador;
    private javax.swing.JTextField codigoLocal;
    private javax.swing.JTextField codigoPartido;
    private javax.swing.JTextField codigoPartidoFk;
    private javax.swing.JTextField codigoVisitante;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JSpinner diaNacJug;
    private javax.swing.JSpinner diaPartido;
    private javax.swing.JSpinner diaPartido1;
    private javax.swing.JTextField dni;
    private javax.swing.JTextField equipoPresidente;
    private javax.swing.JTextField estadio;
    private javax.swing.JSpinner golesLocal;
    private javax.swing.JSpinner golesVisitante;
    private javax.swing.JButton insEquipo;
    private javax.swing.JButton insGol;
    private javax.swing.JButton insJugador;
    private javax.swing.JButton insPartido;
    private javax.swing.JButton insPresidente;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner mesNacJug;
    private javax.swing.JSpinner mesPartido;
    private javax.swing.JSpinner mesPartido1;
    private javax.swing.JSpinner minuto;
    private javax.swing.JTextField nombreEquipo;
    private javax.swing.JTextField nombreJugador;
    private javax.swing.JTextField nombrePresidente;
    private javax.swing.JTextField posicionJugador;
    // End of variables declaration//GEN-END:variables

}
