package Vista;

import Controlador.ControladorEquipo;
import Controlador.ControladorGol;
import Controlador.ControladorJugador;
import Controlador.ControladorPartido;
import Controlador.ControladorPresidente;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author MEDC
 */
public class Insertar extends javax.swing.JFrame {
    ControladorJugador cj;
    ControladorEquipo ce;
    ControladorPartido cpa;
    ControladorPresidente cpr;
    ControladorGol cg;

    /** Creates new form insertar */
    public Insertar() throws SQLException {
        initComponents();
        cj = new ControladorJugador();
        ce = new ControladorEquipo();
        cpa = new ControladorPartido();
        cpr = new ControladorPresidente();
        cg = new ControladorGol();
        this.setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage();
        setIconImage(icon);
        this.setTitle("Insertar datos");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insJugador = new javax.swing.JButton();
        insEquipo = new javax.swing.JButton();
        insPresidente = new javax.swing.JButton();
        insPartido = new javax.swing.JButton();
        insGol = new javax.swing.JButton();
        actGol = new javax.swing.JButton();
        actPresidente = new javax.swing.JButton();
        actPartido = new javax.swing.JButton();
        actEquipo = new javax.swing.JButton();
        actJugador = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        diaNacJug = new javax.swing.JSpinner();
        aforo = new javax.swing.JSpinner();
        añoPresidencia = new javax.swing.JSpinner();
        golesVisitante = new javax.swing.JSpinner();
        golesLocal = new javax.swing.JSpinner();
        minuto = new javax.swing.JSpinner();
        dni = new javax.swing.JTextField();
        nombrePresidente = new javax.swing.JTextField();
        apellidosPresidente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        equipoPresidente = new javax.swing.JTextField();
        nombreEquipo = new javax.swing.JTextField();
        estadio = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        posicionJugador = new javax.swing.JTextField();
        nombreJugador = new javax.swing.JTextField();
        mesNacJug = new javax.swing.JSpinner();
        añoNacJug = new javax.swing.JSpinner();
        mesPartido = new javax.swing.JSpinner();
        diaPartido = new javax.swing.JSpinner();
        añoPartido = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        codigoPartidoFk = new javax.swing.JTextField();
        codigoJugador = new javax.swing.JTextField();
        codigoEquipoFk = new javax.swing.JTextField();
        codigoEquipoPk = new javax.swing.JTextField();
        codigoPartido = new javax.swing.JTextField();
        codigoGol = new javax.swing.JTextField();
        codigoLocal = new javax.swing.JTextField();
        codigoVisitante = new javax.swing.JTextField();
        codigoEquipoFk2 = new javax.swing.JTextField();
        añoFund = new javax.swing.JSpinner();
        mesNacPresi = new javax.swing.JSpinner();
        diaNacPresi = new javax.swing.JSpinner();
        añoNacPresi = new javax.swing.JSpinner();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insJugador.setText("INSERTAR JUGADOR");
        insJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(insJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 147, -1));

        insEquipo.setText("INSERTAR EQUIPO");
        insEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(insEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 700, 150, -1));

        insPresidente.setText("INSERTAR PRESIDENTE");
        insPresidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insPresidenteActionPerformed(evt);
            }
        });
        getContentPane().add(insPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 700, 160, -1));

        insPartido.setText("INSERTAR PARTIDO");
        insPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(insPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 700, 143, -1));

        insGol.setText("INSERTAR GOL");
        insGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insGolActionPerformed(evt);
            }
        });
        getContentPane().add(insGol, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 700, 150, -1));

        actGol.setText("ACTUALIZAR GOL");
        actGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actGolActionPerformed(evt);
            }
        });
        getContentPane().add(actGol, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 730, 150, -1));

        actPresidente.setText("ACTUALIZAR PRESIDENTE");
        actPresidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actPresidenteActionPerformed(evt);
            }
        });
        getContentPane().add(actPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 730, -1, -1));

        actPartido.setText("ACTUALIZAR PARTIDO");
        actPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(actPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 730, -1, -1));

        actEquipo.setText("ACTUALIZAR EQUIPO");
        actEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(actEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 740, 150, 20));

        actJugador.setText("ACTUALIZAR JUGADOR");
        actJugador.setPreferredSize(new java.awt.Dimension(133, 23));
        actJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(actJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 734, 150, -1));

        jLabel9.setText("Estadio");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 37, -1));

        jLabel11.setText("Código Equipo:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel12.setText("Aforo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        jLabel13.setText("Año Fundación");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, -1, -1));

        jLabel14.setText("Nombre del Equipo");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel16.setText("Goles Local:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 100, 20));

        jLabel18.setText("Código Equipo 1");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, -1, -1));

        jLabel19.setText("Código Partido:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jLabel20.setText("Fecha del partido");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        jLabel22.setText("Goles Visitante");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, 20));

        jLabel23.setText("Código Equipo");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 600, -1, -1));

        jLabel24.setText("DNI");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        jLabel25.setText("Fecha Nacimiento");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 110, -1));

        jLabel26.setText("Apellidos");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, -1, -1));
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        jLabel28.setText("Equipo");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, -1, -1));

        jLabel30.setText("Código");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, -1, -1));

        jLabel31.setText("Descripción");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 230, 60, 20));

        jLabel33.setText("Código Partido");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 430, -1, -1));

        jLabel36.setText("Minuto");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 130, -1, -1));

        jLabel37.setText("Código Jugador:");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel38.setText("Fecha Nacimiento");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 110, -1));

        jLabel40.setText("Código Equipo");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        jLabel41.setText("Posición");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jLabel43.setText("Nombre del Jugador");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel44.setText("Ciudad");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, -1));

        jLabel45.setText("Nombre Presidente");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, -1, -1));

        jLabel46.setText("Año presidencia");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, -1, -1));

        jLabel49.setText("Código Equipo 2");
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, -1, -1));

        diaNacJug.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        getContentPane().add(diaNacJug, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        aforo.setModel(new javax.swing.SpinnerNumberModel(4000, 4000, 100000, 1));
        getContentPane().add(aforo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 100, -1));

        añoPresidencia.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, 2000, 1));
        getContentPane().add(añoPresidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, -1, -1));
        getContentPane().add(golesVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));
        getContentPane().add(golesLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        minuto.setModel(new javax.swing.SpinnerNumberModel(1, 1, 120, 1));
        getContentPane().add(minuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 170, -1, -1));
        getContentPane().add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 140, -1));
        getContentPane().add(nombrePresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 150, -1));
        getContentPane().add(apellidosPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 150, -1));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane2.setViewportView(descripcion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 280, 150, 90));
        getContentPane().add(equipoPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 150, -1));
        getContentPane().add(nombreEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 160, -1));
        getContentPane().add(estadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 130, -1));
        getContentPane().add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 120, -1));
        getContentPane().add(posicionJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 160, -1));
        getContentPane().add(nombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, -1));

        mesNacJug.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        getContentPane().add(mesNacJug, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        añoNacJug.setModel(new javax.swing.SpinnerNumberModel(1950, 1950, 2050, 1));
        getContentPane().add(añoNacJug, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        mesPartido.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        getContentPane().add(mesPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        diaPartido.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        getContentPane().add(diaPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        añoPartido.setModel(new javax.swing.SpinnerNumberModel(1950, 1950, 2050, 1));
        getContentPane().add(añoPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 10, 820));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 0, 20, 820));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 10, 820));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 0, 30, 820));
        getContentPane().add(codigoPartidoFk, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, 150, -1));
        getContentPane().add(codigoJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 110, -1));
        getContentPane().add(codigoEquipoFk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 130, -1));
        getContentPane().add(codigoEquipoPk, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 140, -1));
        getContentPane().add(codigoPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 150, -1));
        getContentPane().add(codigoGol, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 60, 140, -1));
        getContentPane().add(codigoLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 130, -1));
        getContentPane().add(codigoVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 120, -1));
        getContentPane().add(codigoEquipoFk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 630, 110, -1));

        añoFund.setModel(new javax.swing.SpinnerNumberModel(1850, 1850, 2050, 1));
        getContentPane().add(añoFund, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 640, 80, -1));

        mesNacPresi.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        getContentPane().add(mesNacPresi, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, -1, -1));

        diaNacPresi.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        getContentPane().add(diaNacPresi, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, -1));

        añoNacPresi.setModel(new javax.swing.SpinnerNumberModel(1950, 1950, 2050, 1));
        getContentPane().add(añoNacPresi, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insJugadorActionPerformed
        // TODO add your handling code here:
        try {
            int codeJugador = Integer.parseInt(codigoJugador.getText());
            int codeEquipo = Integer.parseInt(codigoEquipoFk.getText());
            String nombre = nombreJugador.getText();
            String posicion = posicionJugador.getText();
            String fechaNacimiento = añoNacJug.getValue().toString() + "-" + mesNacJug.getValue().toString() + "-" + diaNacJug.getValue().toString();
            cj.insertarbuscareliminarj("INSERT INTO jugador(codigo, nombre, fech_nacimiento, posicion, codigo_equipo)VALUES('" + codeJugador + "','" + nombre + "','" + fechaNacimiento + "','" + posicion + "','" + codeEquipo + "');");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_insJugadorActionPerformed

    private void actJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actJugadorActionPerformed
        // TODO add your handling code here:
        try {
            int codeJugador = Integer.parseInt(codigoJugador.getText());
            int codeEquipo = Integer.parseInt(codigoEquipoFk.getText());
            String nombre = nombreJugador.getText();
            String posicion = posicionJugador.getText();
            String fechaNacimiento = añoNacJug.getValue().toString() + "-" + mesNacJug.getValue().toString() + "-" + diaNacJug.getValue().toString();
            cj.insertarbuscareliminarj("UPDATE jugador SET nombre='"+nombre+"', fech_nacimiento='"+fechaNacimiento+"',posicion='"+posicion+"', codigo_equipo='"+codeEquipo+"' WHERE codigo='"+codeJugador+"';");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_actJugadorActionPerformed

    private void insEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insEquipoActionPerformed
        // TODO add your handling code here:
        try {
            int codeEquipo = Integer.parseInt(codigoEquipoPk.getText());
            String nombre = nombreEquipo.getText();
            String nombreEstadio = estadio.getText();
            String ciudadEquipo = ciudad.getText();
            int aforoEstadio = (int) aforo.getValue();
            int fundacion = (int) añoFund.getValue();
            ce.insertarbuscareliminarj("INSERT INTO equipo(codigo, nombre_equipo, nombre_estadio, aforo, año_fundacion, ciudad)VALUES('" + codeEquipo + "','" + nombre + "','" + nombreEstadio + "','" + aforoEstadio + "','" + fundacion + "','" + ciudadEquipo + "');");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_insEquipoActionPerformed

    private void actEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actEquipoActionPerformed
        // TODO add your handling code here:
        try {
            int codeEquipo = Integer.parseInt(codigoEquipoPk.getText());
            String nombre = nombreEquipo.getText();
            String nombreEstadio = estadio.getText();
            String ciudadEquipo = ciudad.getText();
            int aforoEstadio = (int) aforo.getValue();
            int fundacion = (int) añoFund.getValue();
            ce.insertarbuscareliminarj("UPDATE equipo SET nombre_equipo='"+nombre+"', nombre_estadio='"+nombreEstadio+"',aforo='"+aforoEstadio+"', año_fundacion='"+fundacion+"', ciudad='"+ciudadEquipo+"' WHERE codigo='"+codeEquipo+"';");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_actEquipoActionPerformed

    private void insPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insPartidoActionPerformed
        // TODO add your handling code here:
        try {
            int codePartido = Integer.parseInt(codigoPartido.getText());
            int codeEquipoLocal = Integer.parseInt(codigoLocal.getText());
            int codeEquipoVisitante = Integer.parseInt(codigoVisitante.getText());
            String resultadoLocal = golesLocal.getValue().toString();
            String resultadoVisitante = golesVisitante.getValue().toString();
            String fechaPartido = añoPartido.getValue().toString() + "-" + mesPartido.getValue().toString() + "-" + diaPartido.getValue().toString();
            cpa.insertarbuscareliminarj("INSERT INTO partidos(codigo, fecha_partido, goles_visitas, goles_casa, codigo_equipo, codigo_equipo2)VALUES('" + codePartido + "','" + fechaPartido + "','" + resultadoVisitante + "','" + resultadoLocal + "','" + codeEquipoLocal + "','" + codeEquipoVisitante + "');");
        } catch (SQLException ex) {
            Logger.getLogger(Insertar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_insPartidoActionPerformed

    private void actPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actPartidoActionPerformed
        // TODO add your handling code here:
        try {
            int codePartido = Integer.parseInt(codigoPartido.getText());
            int codeEquipoLocal = Integer.parseInt(codigoLocal.getText());
            int codeEquipoVisitante = Integer.parseInt(codigoVisitante.getText());
            String resultadoLocal = golesLocal.getValue().toString();
            String resultadoVisitante = golesVisitante.getValue().toString();
            String fechaPartido = añoPartido.getValue().toString() + "-" + mesPartido.getValue().toString() + "-" + diaPartido.getValue().toString();
            cpa.insertarbuscareliminarj("UPDATE partidos SET fecha_partido='"+fechaPartido+"',goles_visitas='"+resultadoVisitante+"', goles_casa='"+resultadoLocal+"',codigo_equipo='"+codeEquipoLocal+"', codigo_equipo2='"+codeEquipoVisitante+"' WHERE codigo='"+codePartido+"';");
        } catch (SQLException ex) {
            Logger.getLogger(Insertar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_actPartidoActionPerformed

    private void insPresidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insPresidenteActionPerformed
        // TODO add your handling code here:
        try {
            String codePresidente = dni.getText();
            String nombre = nombrePresidente.getText();
            String apellidos = apellidosPresidente.getText();
            String equipo = equipoPresidente.getText();
            int codeEquipo = Integer.parseInt(codigoEquipoFk2.getText());
            String presidencia = añoPresidencia.getValue().toString();
            String fechaNacimiento = añoPartido.getValue().toString() + "-" + mesPartido.getValue().toString() + "-" + diaPartido.getValue().toString();
            cpr.insertarbuscareliminarj("INSERT INTO presidentes(dni, nombre, apellidos, fecha_nacimiento, equipo_presidente,año_presidente,codigo_equipo)VALUES('" + codePresidente + "','" + nombre + "','" + apellidos + "','" + fechaNacimiento + "','" + equipo + "','" + presidencia + "','" + codeEquipo + "');");
        } catch (SQLException ex) {
            Logger.getLogger(Insertar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_insPresidenteActionPerformed

    private void actPresidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actPresidenteActionPerformed
        // TODO add your handling code here:
        try {
            String codePresidente = dni.getText();
            String nombre = nombrePresidente.getText();
            String apellidos = apellidosPresidente.getText();
            String equipo = equipoPresidente.getText();
            int codeEquipo = Integer.parseInt(codigoEquipoFk2.getText());
            String presidencia = añoPresidencia.getValue().toString();
            String fechaNacimiento = añoNacPresi.getValue().toString() + "-" + mesNacPresi.getValue().toString() + "-" + diaNacPresi.getValue().toString();
            cpr.insertarbuscareliminarj("UPDATE presidentes SET nombre='"+nombre+"', apellidos='"+apellidos+"',fecha_nacimiento='"+fechaNacimiento+"', equipo_presidente='"+equipo+"',año_presidente='"+presidencia+"',codigo_equipo='"+codeEquipo+"' WHERE dni='"+codePresidente+"';");
        } catch (SQLException ex) {
            Logger.getLogger(Insertar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_actPresidenteActionPerformed

    private void insGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insGolActionPerformed
        // TODO add your handling code here:
        try {
            int codePartido = Integer.parseInt(codigoPartidoFk.getText());
            String descripcionGol = descripcion.getText();
            String minutoGol = minuto.getValue().toString();
            cg.insertarbuscareliminarj("INSERT INTO goles(momento_gol, descripcion_gol, codigo_partido) VALUES ('" + minutoGol + "','" + descripcionGol + "','" + codePartido + "');");
        } catch (SQLException ex) {
            Logger.getLogger(Insertar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_insGolActionPerformed

    private void actGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actGolActionPerformed
        // TODO add your handling code here:
        try {
            int codePartido = Integer.parseInt(codigoPartidoFk.getText());
            String descripcionGol = descripcion.getText();
            String minutoGol = minuto.getValue().toString();
            cg.insertarbuscareliminarj("UPDATE goles SET descripcion_gol='"+descripcionGol+"', codigo_partido='"+codePartido+"' WHERE momento_gol='"+minutoGol+"';");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_actGolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Insertar().setVisible(true);
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actEquipo;
    private javax.swing.JButton actGol;
    private javax.swing.JButton actJugador;
    private javax.swing.JButton actPartido;
    private javax.swing.JButton actPresidente;
    private javax.swing.JSpinner aforo;
    private javax.swing.JTextField apellidosPresidente;
    private javax.swing.JSpinner añoFund;
    private javax.swing.JSpinner añoNacJug;
    private javax.swing.JSpinner añoNacPresi;
    private javax.swing.JSpinner añoPartido;
    private javax.swing.JSpinner añoPresidencia;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField codigoEquipoFk;
    private javax.swing.JTextField codigoEquipoFk2;
    private javax.swing.JTextField codigoEquipoPk;
    private javax.swing.JTextField codigoGol;
    private javax.swing.JTextField codigoJugador;
    private javax.swing.JTextField codigoLocal;
    private javax.swing.JTextField codigoPartido;
    private javax.swing.JTextField codigoPartidoFk;
    private javax.swing.JTextField codigoVisitante;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JSpinner diaNacJug;
    private javax.swing.JSpinner diaNacPresi;
    private javax.swing.JSpinner diaPartido;
    private javax.swing.JTextField dni;
    private javax.swing.JTextField equipoPresidente;
    private javax.swing.JTextField estadio;
    private javax.swing.JSpinner golesLocal;
    private javax.swing.JSpinner golesVisitante;
    private javax.swing.JButton insEquipo;
    private javax.swing.JButton insGol;
    private javax.swing.JButton insJugador;
    private javax.swing.JButton insPartido;
    private javax.swing.JButton insPresidente;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner mesNacJug;
    private javax.swing.JSpinner mesNacPresi;
    private javax.swing.JSpinner mesPartido;
    private javax.swing.JSpinner minuto;
    private javax.swing.JTextField nombreEquipo;
    private javax.swing.JTextField nombreJugador;
    private javax.swing.JTextField nombrePresidente;
    private javax.swing.JTextField posicionJugador;
    // End of variables declaration//GEN-END:variables

}
