package Vista;

import Controlador.ControladorEquipo;
import Controlador.ControladorGol;
import Controlador.ControladorJugador;
import Controlador.ControladorPartido;
import Controlador.ControladorPresidente;
import Controlador.TableControlador;
import Controlador.TableControladorEquipos;
import static com.sun.org.apache.xerces.internal.util.FeatureState.is;
import static com.sun.org.apache.xerces.internal.util.PropertyState.is;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static sun.nio.cs.Surrogate.is;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author MEDC
 */
public class InsEquipo extends javax.swing.JFrame {
    ControladorEquipo ce;
    TableControladorEquipos tbe = new TableControladorEquipos();
   
    /** Creates new form insertar */
    public InsEquipo() throws SQLException {
        initComponents();
        ce = new ControladorEquipo();
        this.setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage();
        setIconImage(icon);
        this.setTitle("Insertar datos");
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insEquipo = new javax.swing.JButton();
        actEquipo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        aforo = new javax.swing.JSpinner();
        nombreEquipo = new javax.swing.JTextField();
        estadio = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        codigoEquipoPk = new javax.swing.JTextField();
        añoFund = new javax.swing.JSpinner();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insEquipo.setText("INSERTAR EQUIPO");
        insEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(insEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 150, 30));

        actEquipo.setText("ACTUALIZAR EQUIPO");
        actEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(actEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 150, 30));

        jLabel9.setText("Estadio");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 50, -1));

        jLabel11.setText("Código Equipo:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel12.setText("Aforo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel13.setText("Año Fundación");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jLabel14.setText("Nombre del Equipo");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        jLabel44.setText("Ciudad");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        aforo.setModel(new javax.swing.SpinnerNumberModel(4000, 4000, 100000, 1));
        getContentPane().add(aforo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 100, -1));
        getContentPane().add(nombreEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, -1));
        getContentPane().add(estadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, -1));
        getContentPane().add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 120, -1));
        getContentPane().add(codigoEquipoPk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, -1));

        añoFund.setModel(new javax.swing.SpinnerNumberModel(1850, 1850, 2050, 1));
        getContentPane().add(añoFund, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insEquipoActionPerformed
   try {
            
            if((codigoEquipoPk.getText().length()==0)|| (nombreEquipo.getText().length()==0) || (estadio.getText().length()==0) || (ciudad.getText().length()==0)){
                JOptionPane.showMessageDialog(null,"No se han insertado los datos correctamente");
            
            }else{
                int codeEquipo = Integer.parseInt(codigoEquipoPk.getText());
                String nombre = nombreEquipo.getText();
                String nombreEstadio = estadio.getText();
                String ciudadEquipo = ciudad.getText();
                int aforoEstadio = (int) aforo.getValue();
                int fundacion = (int) añoFund.getValue();
                ce.insertarbuscareliminarj("INSERT INTO equipo(codigo, nombre_equipo, nombre_estadio, aforo, año_fundacion, ciudad)VALUES('" + codeEquipo + "','" + nombre + "','" + nombreEstadio + "','" + aforoEstadio + "','" + fundacion + "','" + ciudadEquipo + "');");
                JOptionPane.showMessageDialog(null, "Se ha insertado correctamente");
                codigoEquipoPk.setText("");
                nombreEquipo.setText("");
                estadio.setText("");
                ciudad.setText("");
                tbe.cargarEquipo();
            }
            
            
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_insEquipoActionPerformed

    private void actEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actEquipoActionPerformed
       try {
            if((codigoEquipoPk.getText().length()==0)|| (nombreEquipo.getText().length()==0) || (estadio.getText().length()==0) || (ciudad.getText().length()==0)){
                JOptionPane.showMessageDialog(null,"No se han insertado los datos correctamente");
            
            }else{
            int codeEquipo = Integer.parseInt(codigoEquipoPk.getText());
            String nombre = nombreEquipo.getText();
            String nombreEstadio = estadio.getText();
            String ciudadEquipo = ciudad.getText();
            int aforoEstadio = (int) aforo.getValue();
            int fundacion = (int) añoFund.getValue();
            ce.insertarbuscareliminarj("UPDATE equipo SET nombre_equipo='"+nombre+"', nombre_estadio='"+nombreEstadio+"',aforo='"+aforoEstadio+"', año_fundacion='"+fundacion+"', ciudad='"+ciudadEquipo+"' WHERE codigo='"+codeEquipo+"';");
            codigoEquipoPk.setText("");
            nombreEquipo.setText("");
            estadio.setText("");
            ciudad.setText("");
            JOptionPane.showMessageDialog(null, "Se ha Actualizado correctamente");
            tbe.cargarEquipo();
            
            }
            } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_actEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InsEquipo().setVisible(true);
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actEquipo;
    private javax.swing.JSpinner aforo;
    private javax.swing.JSpinner añoFund;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField codigoEquipoPk;
    private javax.swing.JTextField estadio;
    private javax.swing.JButton insEquipo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombreEquipo;
    // End of variables declaration//GEN-END:variables

}
