package Vista;

import Controlador.ControladorEquipo;
import Controlador.ControladorGol;
import Controlador.ControladorJugador;
import Controlador.ControladorPartido;
import Controlador.ControladorPresidente;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author MEDC
 */
public class InsGol extends javax.swing.JFrame {
    ControladorGol cg;

    /** Creates new form insertar */
    public InsGol() throws SQLException {
        initComponents();
        cg = new ControladorGol();
        this.setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage();
        setIconImage(icon);
        this.setTitle("Insertar datos");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insGol = new javax.swing.JButton();
        actGol = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        minuto = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        codigoPartidoFk = new javax.swing.JTextField();
        codigoGol = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insGol.setText("INSERTAR GOL");
        insGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insGolActionPerformed(evt);
            }
        });
        getContentPane().add(insGol, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 150, -1));

        actGol.setText("ACTUALIZAR GOL");
        actGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actGolActionPerformed(evt);
            }
        });
        getContentPane().add(actGol, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 150, -1));
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        jLabel30.setText("Código");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel31.setText("Descripción");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 60, 20));

        jLabel33.setText("Código Partido");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel36.setText("Minuto");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        minuto.setModel(new javax.swing.SpinnerNumberModel(1, 1, 120, 1));
        getContentPane().add(minuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane2.setViewportView(descripcion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 200, 120));
        getContentPane().add(codigoPartidoFk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, -1));
        getContentPane().add(codigoGol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insGolActionPerformed
       
       try {
           
            if((codigoGol.getText().length()==0)|| (codigoPartidoFk.getText().length()==0) || (descripcion.getText().length()==0)){
                JOptionPane.showMessageDialog(null,"No se han insertado los datos correctamente");
            
            }else{
            
            int codePartido = Integer.parseInt(codigoPartidoFk.getText());
            String descripcionGol = descripcion.getText();
            String minutoGol = minuto.getValue().toString();
            cg.insertarbuscareliminarj("INSERT INTO goles(momento_gol, descripcion_gol, codigo_partido) VALUES ('" + minutoGol + "','" + descripcionGol + "','" + codePartido + "');");
            codigoGol.setText("");
            descripcion.setText("");
            codigoPartidoFk.setText("");
            JOptionPane.showMessageDialog(null,"Se ha insertado Correctamente");

            }
            } catch (SQLException ex) {
            Logger.getLogger(InsGol.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_insGolActionPerformed

    private void actGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actGolActionPerformed
          try {
             if((codigoGol.getText().length()==0)|| (codigoPartidoFk.getText().length()==0) || (descripcion.getText().length()==0)){
                JOptionPane.showMessageDialog(null,"No se han insertado los datos correctamente");
            
            }else{
            int codePartido = Integer.parseInt(codigoPartidoFk.getText());
            String descripcionGol = descripcion.getText();
            String minutoGol = minuto.getValue().toString();
            cg.insertarbuscareliminarj("UPDATE goles SET descripcion_gol='"+descripcionGol+"', codigo_partido='"+codePartido+"' WHERE momento_gol='"+minutoGol+"';");
            codigoGol.setText("");
            descripcion.setText("");
            codigoPartidoFk.setText("");
            JOptionPane.showMessageDialog(null,"Se ha actualizado correctamente");
            
            
            
            }
            } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_actGolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsGol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsGol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsGol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsGol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InsGol().setVisible(true);
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actGol;
    private javax.swing.JTextField codigoGol;
    private javax.swing.JTextField codigoPartidoFk;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JButton insGol;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner minuto;
    // End of variables declaration//GEN-END:variables

}
