package Vista;

import Controlador.ControladorEquipo;
import Controlador.ControladorGol;
import Controlador.ControladorJugador;
import Controlador.ControladorPartido;
import Controlador.ControladorPresidente;
import Controlador.TableControlador3;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author MEDC
 */
public class InsPresidente extends javax.swing.JFrame {
    ControladorPresidente cpr;
    TableControlador3 tb3 = new TableControlador3();

    /** Creates new form insertar */
    public InsPresidente() throws SQLException {
        initComponents();
        cpr = new ControladorPresidente();
        this.setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage();
        setIconImage(icon);
        this.setTitle("Insertar datos");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insPresidente = new javax.swing.JButton();
        actPresidente = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        añoPresidencia = new javax.swing.JSpinner();
        dni = new javax.swing.JTextField();
        nombrePresidente = new javax.swing.JTextField();
        apellidosPresidente = new javax.swing.JTextField();
        equipoPresidente = new javax.swing.JTextField();
        codigoEquipoFk2 = new javax.swing.JTextField();
        mesNacPresi = new javax.swing.JSpinner();
        diaNacPresi = new javax.swing.JSpinner();
        añoNacPresi = new javax.swing.JSpinner();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insPresidente.setText("INSERTAR PRESIDENTE");
        insPresidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insPresidenteActionPerformed(evt);
            }
        });
        getContentPane().add(insPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 180, 30));

        actPresidente.setText("ACTUALIZAR PRESIDENTE");
        actPresidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actPresidenteActionPerformed(evt);
            }
        });
        getContentPane().add(actPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 180, 30));

        jLabel23.setText("Código Equipo");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 80, -1));

        jLabel24.setText("DNI");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel25.setText("Fecha Nacimiento");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 110, -1));

        jLabel26.setText("Apellidos");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        jLabel28.setText("Equipo");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        jLabel45.setText("Nombre Presidente");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel46.setText("Año presidencia");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        añoPresidencia.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, 2000, 1));
        getContentPane().add(añoPresidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));
        getContentPane().add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, -1));
        getContentPane().add(nombrePresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, -1));
        getContentPane().add(apellidosPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, -1));
        getContentPane().add(equipoPresidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 150, -1));
        getContentPane().add(codigoEquipoFk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, -1));

        mesNacPresi.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        getContentPane().add(mesNacPresi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        diaNacPresi.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        getContentPane().add(diaNacPresi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        añoNacPresi.setModel(new javax.swing.SpinnerNumberModel(1950, 1950, 2050, 1));
        getContentPane().add(añoNacPresi, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insPresidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insPresidenteActionPerformed
         try {
             if((dni.getText().length()==0) ||(nombrePresidente.getText().length()==0) || (apellidosPresidente.getText().length()==0) || (codigoEquipoFk2.getText().length()==0) || (equipoPresidente.getText().length()==0)){
             JOptionPane.showMessageDialog(null,"No se han insertado los datos correctamente");
             }else{
            String codePresidente = dni.getText();
            String nombre = nombrePresidente.getText();
            String apellidos = apellidosPresidente.getText();
            String equipo = equipoPresidente.getText();
            int codeEquipo = Integer.parseInt(codigoEquipoFk2.getText());
            String presidencia = añoPresidencia.getValue().toString();
            String fechaNacimiento = añoNacPresi.getValue().toString() + "-" + mesNacPresi.getValue().toString() + "-" + diaNacPresi.getValue().toString();
            cpr.insertarbuscareliminarj("INSERT INTO presidentes(dni, nombre, apellidos, fecha_nacimiento, equipo_presidente,año_presidente,codigo_equipo)VALUES('" + codePresidente + "','" + nombre + "','" + apellidos + "','" + fechaNacimiento + "','" + equipo + "','" + presidencia + "','" + codeEquipo + "');");
            JOptionPane.showMessageDialog(null, "Se ha insertado correctamente");
            dni.setText("");
            nombrePresidente.setText("");
            apellidosPresidente.setText("");
            codigoEquipoFk2.setText("");
            equipoPresidente.setText("");
            tb3.cargarPresidente();
            }
            } catch (SQLException ex) {
            Logger.getLogger(InsPresidente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_insPresidenteActionPerformed

    private void actPresidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actPresidenteActionPerformed
        try {
             if((dni.getText().length()==0) ||(nombrePresidente.getText().length()==0) || (apellidosPresidente.getText().length()==0) || (codigoEquipoFk2.getText().length()==0) || (equipoPresidente.getText().length()==0)){
             JOptionPane.showMessageDialog(null,"No se han insertado los datos correctamente");
             }else{
            String codePresidente = dni.getText();
            String nombre = nombrePresidente.getText();
            String apellidos = apellidosPresidente.getText();
            String equipo = equipoPresidente.getText();
            int codeEquipo = Integer.parseInt(codigoEquipoFk2.getText());
            String presidencia = añoPresidencia.getValue().toString();
            String fechaNacimiento = añoNacPresi.getValue().toString() + "-" + mesNacPresi.getValue().toString() + "-" + diaNacPresi.getValue().toString();
            cpr.insertarbuscareliminarj("UPDATE presidentes SET nombre='"+nombre+"', apellidos='"+apellidos+"',fecha_nacimiento='"+fechaNacimiento+"', equipo_presidente='"+equipo+"',año_presidente='"+presidencia+"',codigo_equipo='"+codeEquipo+"' WHERE dni='"+codePresidente+"';");
            JOptionPane.showMessageDialog(null, "Se ha actualizado correctamente");
            dni.setText("");
            nombrePresidente.setText("");
            apellidosPresidente.setText("");
            codigoEquipoFk2.setText("");
            equipoPresidente.setText(""); 
            tb3.cargarPresidente();
             
            }
             
             } catch (SQLException ex) {
            Logger.getLogger(InsPresidente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_actPresidenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsPresidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsPresidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsPresidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsPresidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InsPresidente().setVisible(true);
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actPresidente;
    private javax.swing.JTextField apellidosPresidente;
    private javax.swing.JSpinner añoNacPresi;
    private javax.swing.JSpinner añoPresidencia;
    private javax.swing.JTextField codigoEquipoFk2;
    private javax.swing.JSpinner diaNacPresi;
    private javax.swing.JTextField dni;
    private javax.swing.JTextField equipoPresidente;
    private javax.swing.JButton insPresidente;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JSpinner mesNacPresi;
    private javax.swing.JTextField nombrePresidente;
    // End of variables declaration//GEN-END:variables

}
