package Vista;

import Controlador.ControladorEquipo;
import Controlador.ControladorGol;
import Controlador.ControladorJugador;
import Controlador.ControladorPartido;
import Controlador.ControladorPresidente;
import Controlador.TableControlador;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author MEDC
 */
public class InsPartido extends javax.swing.JFrame {
    ControladorPartido cpa;
    TableControlador tb= new TableControlador();

    /** Creates new form insertar */
    public InsPartido() throws SQLException {
        initComponents();
        cpa = new ControladorPartido();
        this.setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage();
        setIconImage(icon);
        this.setTitle("Insertar datos");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insPartido = new javax.swing.JButton();
        actPartido = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        golesVisitante = new javax.swing.JSpinner();
        golesLocal = new javax.swing.JSpinner();
        mesPartido = new javax.swing.JSpinner();
        diaPartido = new javax.swing.JSpinner();
        añoPartido = new javax.swing.JSpinner();
        codigoPartido = new javax.swing.JTextField();
        codigoLocal = new javax.swing.JTextField();
        codigoVisitante = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insPartido.setText("INSERTAR PARTIDO");
        insPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(insPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 242, 150, 30));

        actPartido.setText("ACTUALIZAR PARTIDO");
        actPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(actPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, 30));

        jLabel16.setText("Goles Local:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 20));

        jLabel18.setText("Código Equipo 1");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel19.setText("Código Partido:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel20.setText("Fecha del partido");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel22.setText("Goles Visitante");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 20));
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        jLabel49.setText("Código Equipo 2");
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));
        getContentPane().add(golesVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));
        getContentPane().add(golesLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        mesPartido.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        getContentPane().add(mesPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        diaPartido.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        getContentPane().add(diaPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        añoPartido.setModel(new javax.swing.SpinnerNumberModel(1950, 1950, 2050, 1));
        getContentPane().add(añoPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));
        getContentPane().add(codigoPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, -1));
        getContentPane().add(codigoLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 130, -1));
        getContentPane().add(codigoVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insPartidoActionPerformed
      try {
            if(codigoPartido.getText().length()==0||codigoLocal.getText().length()==0||codigoVisitante.getText().length()==0){
                JOptionPane.showMessageDialog(null,"No se han insertado los datos correctamente");
                
            }
            else{
                Consultarpartidos consp = new Consultarpartidos();
                int codePartido = Integer.parseInt(codigoPartido.getText());
                int codeEquipoLocal = Integer.parseInt(codigoLocal.getText());
                int codeEquipoVisitante = Integer.parseInt(codigoVisitante.getText());
                String resultadoLocal = golesLocal.getValue().toString();
                String resultadoVisitante = golesVisitante.getValue().toString();
                String fechaPartido = añoPartido.getValue().toString() + "-" + mesPartido.getValue().toString() + "-" + diaPartido.getValue().toString();
                cpa.insertarbuscareliminarj("INSERT INTO partidos(codigo, fecha_partido, goles_visitas, goles_casa, codigo_equipo, codigo_equipo2)VALUES('" + codePartido + "','" + fechaPartido + "','" + resultadoVisitante + "','" + resultadoLocal + "','" + codeEquipoLocal + "','" + codeEquipoVisitante + "');");
                JOptionPane.showMessageDialog(null,"Se han insertado los datos correctamente");
                codigoLocal.setText("");
                codigoVisitante.setText("");      
                codigoPartido.setText("");
                consp.setVisible(true);
                try{
                    tb.cargarPartido();
                }catch(Exception e){
                    System.out.println(e);
                }
                
                this.setVisible(false);
            
            }
            } catch (SQLException ex) {
                Logger.getLogger(InsPartido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_insPartidoActionPerformed

    private void actPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actPartidoActionPerformed
       
          try {
             if(codigoPartido.getText().length()==0||codigoLocal.getText().length()==0||codigoVisitante.getText().length()==0){
                JOptionPane.showMessageDialog(null,"No se han insertado los datos correctamente");
                
            }
            else{
            Consultarpartidos consp = new Consultarpartidos();
            int codePartido = Integer.parseInt(codigoPartido.getText());
            int codeEquipoLocal = Integer.parseInt(codigoLocal.getText());
            int codeEquipoVisitante = Integer.parseInt(codigoVisitante.getText());
            String resultadoLocal = golesLocal.getValue().toString();
            String resultadoVisitante = golesVisitante.getValue().toString();
            String fechaPartido = añoPartido.getValue().toString() + "-" + mesPartido.getValue().toString() + "-" + diaPartido.getValue().toString();
            cpa.insertarbuscareliminarj("UPDATE partidos SET fecha_partido='"+fechaPartido+"',goles_visitas='"+resultadoVisitante+"', goles_casa='"+resultadoLocal+"',codigo_equipo='"+codeEquipoLocal+"', codigo_equipo2='"+codeEquipoVisitante+"' WHERE codigo='"+codePartido+"';");
            JOptionPane.showMessageDialog(null, "Se ha actualizado correctamente");
            codigoLocal.setText("");
            codigoVisitante.setText("");      
            codigoPartido.setText("");
            consp.setVisible(true);
             try{
                    tb.cargarPartido();
                }catch(Exception e){
                    System.out.println(e);
                }
                
                this.setVisible(false);
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(InsPartido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_actPartidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InsPartido().setVisible(true);
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actPartido;
    private javax.swing.JSpinner añoPartido;
    private javax.swing.JTextField codigoLocal;
    private javax.swing.JTextField codigoPartido;
    private javax.swing.JTextField codigoVisitante;
    private javax.swing.JSpinner diaPartido;
    private javax.swing.JSpinner golesLocal;
    private javax.swing.JSpinner golesVisitante;
    private javax.swing.JButton insPartido;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JSpinner mesPartido;
    // End of variables declaration//GEN-END:variables

}
